version: '3.8'

services:
  gateway:
    build:
      context: ../../backend/gateway-service
      dockerfile: ../../infra/docker/Dockerfile.gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - kafka

  ride-service:
    build:
      context: ../../backend/ride-service
      dockerfile: ../../infra/docker/Dockerfile.ride
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/rides
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
